name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_gui:
    name: 'Build GUI App'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Install Dependencies
        run: |
          nuget restore SoMRandomizer.gui.sln
      - name: Build Debug
        run: |
          msbuild SoMRandomizer.gui.sln
          ls SoMRandomizer.gui\bin\Debug\net462
      - name: Store Debug
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizer-Debug
          path: |
            SoMRandomizer.gui/bin/Debug/net462/SoMRandomizer*.exe
            SoMRandomizer.gui/bin/Debug/net462/SoMRandomizer*.pdb
          if-no-files-found: error
          compression-level: 9
          retention-days: 7
      - name: Build Release
        run: |
          msbuild SoMRandomizer.gui.sln /p:Configuration=Release
          ls SoMRandomizer.gui\bin\Release\net462
      - name: Store Release
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizer-Release
          path: |
            SoMRandomizer.gui/bin/Release/net462/SoMRandomizer*.exe
          if-no-files-found: error
          compression-level: 9
          retention-days: 7

  build_cli:
    name: 'Build CLI App on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2025, windows-11-arm, macos-15]
        # TODO: universal2 ("fat") binary on macos

    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: '10'
      - name: Install Dependencies
        run: |
          dotnet restore SoMRandomizer.cli.sln
      - name: Publish
        run: |
          dotnet publish SoMRandomizer.cli.sln
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: 'SoMRandomizer-cli_${{ runner.os }}-${{ runner.arch }}'
          path: |
            SoMRandomizer.cli/bin/Release/**/native/*
          if-no-files-found: error
          compression-level: 9
          retention-days: 7

  test_api:
    # NOTE: we don't upload the API build in CI, but we still want to test it
    name: 'Build API and run tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: '10'
      - name: Install Dependencies
        run: |
          dotnet restore SoMRandomizer.api.sln
      - name: Build
        run: |
          # build in two steps and the second with just 1 core, because we run into this otherwise:
          # https://github.com/dotnet/sdk/issues/2902
          dotnet build SoMRandomizer.api/ --no-restore
          dotnet build SoMRandomizer.api.Tests/ --no-restore -maxcpucount:1
      - name: Test
        run: |
          dotnet test SoMRandomizer.api.sln --no-restore --no-build
