name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Install Dependencies
        run: |
          nuget restore
      - name: Build Debug
        run: |
          msbuild
          ls SoMRandomizer\bin\Debug
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizer-Debug
          path: SomRandomizer/bin/Debug/SoMRandomizer.*
          if-no-files-found: error
          compression-level: 9
          retention-days: 7

  build-cli:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build Publish
        run: |
          cd SoMRandomizerDotNetStandard/SoMRandomizerCLI
          dotnet publish -a ${{ matrix.arch }}
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizerCLI-${{ runner.os }}-${{ matrix.arch }}
          path: SoMRandomizerDotNetStandard/SoMRandomizerCLI/bin/Release/*/*/native/*
          if-no-files-found: error
          compression-level: 9
          retention-days: 7
