name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_gui:
    name: 'Build GUI App'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Install Dependencies
        run: |
          nuget restore SoMRandomizer.gui.sln
      - name: Build Debug
        run: |
          msbuild SoMRandomizer.gui.sln
          ls SoMRandomizer.gui\bin\Debug\net462
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizer-Debug
          path: |
            SoMRandomizer.gui/bin/Debug/net462/SoMRandomizer*.exe
            SoMRandomizer.gui/bin/Debug/net462/SoMRandomizer*.pdb
          if-no-files-found: error
          compression-level: 9
          retention-days: 7
